# Generated by Django 3.1.3 on 2020-11-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Imagen'),
        ),
    ]
